# Generated by Django 3.2.10 on 2023-02-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('andrewid', models.CharField(max_length=50)),
                ('onIsland', models.BooleanField(default=False)),
                ('lastActive', models.DateTimeField()),
            ],
        ),
    ]
