# Generated by Django 3.2.10 on 2023-02-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypenguin', '0004_auto_20230204_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastActive',
            field=models.DateTimeField(default=None),
        ),
    ]
