# Generated by Django 3.2.10 on 2023-02-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypenguin', '0005_alter_user_lastactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='islandNum',
            field=models.IntegerField(default=0),
        ),
    ]
